var bots = [
  "@secratorybot",
  "@Ytube_mp3_bot",
  "@carbonnow_bot",
  "@Cyber_space_bot",
  "@phonecalltrackerbot",
  "@venila_telegraph_bot"
];
// '/' means anyone can use it
// '-' means admins can use it
var commands = [
  {
    "/afk": "Mark yourself as AFK.",
    "/adminlist": " list of admins in the chat",
    "-pin": "silently pins the message replied to - add 'loud' or 'notify' to give notifs to users",
    "-unpin": "unpins the currently pinned message",
    "-invitelink": "gets invitelink",
    "-promote": "promotes the user replied to",
    "-demote": "demotes the user replied to",
    "-approval": " Check a user's approval status in this chat.",
    "-approve": "Approve of a user. Locks, blacklists, and antiflood won't apply to them anymore.",
    "-unapprove": "Unapprove of a user. They will now be subject to locks, blacklists, and antiflood again.",
    "-approved": "List all approved users.",
    "-import": "reply to a group butler backup file to import as much as possible, making the transfer super simple! Note that files/photos can't be imported due to telegram restrictions.",
    "-export": "export group data, which will be exported are: rules, notes (documents, images, music, video, audio, voice, text, text buttons)",
    "/kinkme": "kicks the user who issued the command",
    "-ban": " bans a user. (via handle, or reply)",
    "-tban": "bans a user for x time. (via handle, or reply). m = minutes, h = hours, d = days.",
    "/unban": "unbans a user. (via handle, or reply)",
    "/kick": "kicks a user, (via handle, or reply)",
    "/setbio": "while replying, will save another user's bio",
    "/bio": "will get your or another user's bio. This cannot be set by yourself.",
    "/setme": "will set your info",
    "/me": "will get your or another user's info",
    "/cmds": "check the current status of disabled commands",
    "-enable": " enable that command",
    "-disable": " disable that command",
    "-listcmds": "list all possible toggleable commands",
    "/connect": " Connect to remote chat",
    "/disconnect": " Disconnect from chat",
    "/allowconnect": "Allow connect users to group",
    "/shrug": "get shrug",
    "/table": "get flip/unflip",
    "/decide": "Randomly answers yes/no/maybe",
    "/toss": "Tosses A coin",
    "/tts": "Converts text to speech",
    "/roll": " Roll a dice.",
    "/rlg": " Join ears,nose,mouth and create an emo",
    "/zal": "zalgofy! your text",
    "/filters": " list all active filters in this chat.",
    "-filter": "add a filter to this chat. The bot will now reply that message whenever 'keyword'is mentioned. If you reply to a sticker with a keyword, the bot will reply with that sticker. NOTE: all filter keywords are in lowercase. If you want your keyword to be a sentence, use quotes.",
    "-stop": "stop that filter.",
    "/flood": "To know your current message control.",
    "-setflood": "enables or disables flood control",
    "-gbanstat": "Will disable the effect of global bans on your group, or return your current settings.",
    "-gmutestat": " Will disable the effect of global mutes on your group, or return your current settings. Gmutes, also known as global mutes, are used by the bot owners to mute spammers across all groups. This helps protect you and your groups by removing spam flooders as quickly as possible. They can be disabled for you group by calling /gmutestat",
    "/locktypes": "a list of possible locktypes",
    "-lock": " lock items of a certain type (not available in private)",
    "-unlock": "unlock items of a certain type (not available in private)",
    "-locks": "the current list of locks in this chat.",
    "/id": "get the current group id. If used by replying to a message, gets that user's id.",
    "/runs": "reply a random string from an array of replies.",
    "/slap": "slap a user, or get slapped if not a reply.",
    "/time": " gives the local time at the given place.",
    "/info": "get information about a user.",
    "/gdrp": "deletes your information from the bot's database. Private chats only.",
    "/markdownhelp": "quick summary of how markdown works in telegram - can only be called in private chats.",
    "/stickerid": "reply to a sticker and get sticker id of that.",
    "/getsticker": "reply to a sticker and get that sticker as .png and image.",
    "-mute": " silences a user. Can also be used as a reply, muting the replied to user.",
    "-tmute": "mutes a user for x time. (via handle, or reply). m = minutes, h = hours, d = days.",
    "-unmute": "unmutes a user. Can also be used as a reply, muting the replied to user.",
    "/get": "",
    "/notes": "",
    "/saved": "",
    "-save": "",
    "-clear": "",
    "-del": "",
    "-purge": "",
    "/rules": "",
    "-setrules": "",
    "-clearrules": "",
    "/addrss": "",
    "/removerss": "",
    "/rss": "",
    "/listrss": "",
    "/report": "",
    "/reports": "",
    "@admins": "",
    "/telegraph": "",
    "/tele.gra.ph": "",
    "/t": "",
    "/ud": "",
    "/warns": "",
    "/warnlist": "",
    "-warn": "",
    "-resetwarn": "",
    "-addwarn": "",
    "-nowarn": "",
    "-warnlimit": "",
    "-strongwarn": "",
    "-welcome": "",
    "-goodbye": "",
    "-setwelcome": "",
    "-setgoodbye": "",
    "-resetwelcome": "",
    "-resetgoodbye": "",
    "-cleanwelcome": "",
    "-clearjoin": "",
    "-welcomehelp": ""
  }
]